"""initial schema

Revision ID: 7499bfdf84fe
Revises: 
Create Date: 2026-09-24 18:57:01.587297
"""
from alembic import op
import sqlalchemy as sa


revision = '7499bfdf84fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=True),
    sa.Column('input_preview', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('safety_guides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('read_minutes', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_guides_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_guides_slug'), ['slug'], unique=True)

    op.create_table('scam_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scam_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scam_locations_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_scam_locations_slug'), ['slug'], unique=True)

    op.create_table('analysis_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_evidence_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('scam_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scam_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_lost', sa.Float(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_path', sa.String(length=255), nullable=True),
    sa.Column('evidence_mime', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['scam_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scam_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scam_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scam_reports_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_scam_reports_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scam_reports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scam_reports_scam_type'), ['scam_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scam_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scam_reports_scam_type'))
        batch_op.drop_index(batch_op.f('ix_scam_reports_public_id'))
        batch_op.drop_index(batch_op.f('ix_scam_reports_location_id'))
        batch_op.drop_index(batch_op.f('ix_scam_reports_is_demo'))
        batch_op.drop_index(batch_op.f('ix_scam_reports_created_at'))

    op.drop_table('scam_reports')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_analysis_id'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('analysis_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_evidence_analysis_id'))

    op.drop_table('analysis_evidence')
    with op.batch_alter_table('scam_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scam_locations_slug'))
        batch_op.drop_index(batch_op.f('ix_scam_locations_region'))

    op.drop_table('scam_locations')
    with op.batch_alter_table('safety_guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_guides_slug'))
        batch_op.drop_index(batch_op.f('ix_safety_guides_category'))

    op.drop_table('safety_guides')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_analyses_client_id'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
