from __future__ import annotations

import re

from fastapi import Header

from app.core.errors import SentinelError

_CLIENT_RE = re.compile(r"^[A-Za-z0-9-]{8,64}$")


def optional_client_id(x_sentinel_client: str | None = Header(default=None)) -> str | None:
    """Anonymous device id generated by the browser. Never tied to identity."""
    if x_sentinel_client and _CLIENT_RE.match(x_sentinel_client):
        return x_sentinel_client
    return None


def required_client_id(x_sentinel_client: str | None = Header(default=None)) -> str:
    cid = optional_client_id(x_sentinel_client)
    if not cid:
        raise SentinelError("CLIENT_ID_REQUIRED", "This device's history identifier is missing.", 400)
    return cid
